steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/cluster-test-356718/bootcamp/adservice:$SHORT_SHA', 'src/adservice' ]
images:
- 'europe-west1-docker.pkg.dev/cluster-test-356718/bootcamp/adservice:$SHORT_SHA'