apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: adservice
          image: europe-west1-docker.pkg.dev/k8s-formation/bootcamp/benjamin/adservice:test
          ports:
            - containerPort: 9555
              protocol: TCP
              name: grpc
          env:
            - name: PORT
              value: "9555"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
          readinessProbe:
            initialDelaySeconds: 0
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: ad
spec:
  selector:
    app: adservice
  ports:
    - port: 9555
      name: grpc