resources:
  - ../../base
namespace: bootcamp-prod
commonLabels:
  env: production
patchesStrategicMerge:
  - patch-adservice.yaml
images:
  - name: europe-west1-docker.pkg.dev/bootcamp-app-364615/bootcamp/adservice
    newTag: "2.0"